apiVersion: v1
kind: Service
metadata:
  name: demo-prometheus-service
spec:
  selector:
    app: demo-prometheus
  ports:
    - name: prometheus 
      protocol: TCP
      port: 9090
      targetPort: 9090
  clusterIP: 10.0.103.183
  type: LoadBalancer