apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-prometheus
  labels:
    app: demo-prometheus
spec:
  selector:
    matchLabels:
      app: demo-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-prometheus
    spec:
      containers:
      - name: demo-prometheus
        image: docker.io/prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
         - name: prometheus-config
           mountPath: /etc/prometheus
      volumes:
       - name: prometheus-config
         configMap:
           name: prometheus-configmap